import { useEffect, useRef, useState } from 'react'
const api = 'http://localhost:5138'
type Child={id:string;name:string;birthDate:string}
type Question={id:string;questionType:string;instruction:string;questionText:string;stimulusJson?:string}
type State='Ready'|'Presenting'|'RetentionGap'|'Responding'|'Submitting'|'Complete'
export default function WorkingMemoryPlayer(){
 const [children,setChildren]=useState<Child[]>([]),[child,setChild]=useState(''),[session,setSession]=useState(''),[q,setQ]=useState<Question|null>(null),[state,setState]=useState<State>('Ready'),[response,setResponse]=useState<string[]>([]),[shown,setShown]=useState<string>(''),started=useRef(0),timers=useRef<number[]>([])
 const clear=()=>{timers.current.forEach(clearTimeout);timers.current=[];speechSynthesis.cancel()}; useEffect(()=>{fetch(`${api}/api/children`).then(r=>r.json()).then(setChildren);return clear},[])
 const begin=async()=>{const b=await fetch(`${api}/api/assessment-blueprints`).then(r=>r.json());const s=await fetch(`${api}/api/assessments/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({childId:child,blueprintId:b[0].id})}).then(r=>r.json());setSession(s.id);next(s.id)}
 const next=async(s=session)=>{clear();setResponse([]);setShown('');const r=await fetch(`${api}/api/assessments/${s}/next-question`);if(r.status===204){setState('Complete');return}const n=await r.json() as Question;setQ(n);present(n)}
 const present=(n:Question)=>{const x=JSON.parse(n.stimulusJson||'{}'),seq:string[]=x.sequence||[],duration=x.presentationDurationMs||900,gap=x.retentionGapMs||900;setState('Presenting');let i=0;const show=()=>{setShown(seq[i]||'');if(i++<seq.length-1)timers.current.push(window.setTimeout(show,duration));else timers.current.push(window.setTimeout(()=>{setShown('');setState('RetentionGap');timers.current.push(window.setTimeout(()=>{setState('Responding');started.current=performance.now()},gap))},duration))}; if(n.questionType==='AuditorySequence'||n.questionType==='InstructionSequence'){const u=new SpeechSynthesisUtterance(seq.join(', '));u.lang='id-ID';u.onend=()=>{setState('RetentionGap');timers.current.push(window.setTimeout(()=>{setState('Responding');started.current=performance.now()},gap))};speechSynthesis.speak(u)}else show()}
 const options=()=>JSON.parse(q?.stimulusJson||'{}').sequence||[]; const tap=(v:string)=>state==='Responding'&&setResponse(r=>[...r,v]); const submit=async()=>{if(!q||state!=='Responding')return;setState('Submitting');await fetch(`${api}/api/assessments/${session}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,answer:JSON.stringify(response),responseTimeMs:Math.max(1,Math.round(performance.now()-started.current)),firstInteraction:true})});next()}
 return <section className="player"><h2>Working Memory</h2>{state==='Ready'&&<><select value={child} onChange={e=>setChild(e.target.value)}><option value="">Pilih anak</option>{children.map(c=><option value={c.id}>{c.name}</option>)}</select><button disabled={!child} onClick={begin}>Mulai</button></>}{q&&state!=='Ready'&&state!=='Complete'&&<><p>{q.instruction}</p><h2>{state==='Presenting'?shown:state==='RetentionGap'?'Tunggu sebentar…':'Susun ulang urutan'}</h2>{state==='Responding'&&<><p>Jawaban: {response.join(' → ')||'—'}</p><div className="options">{options().map((v:string,i:number)=>q.questionType==='SpatialMemory'?<button onClick={()=>tap(v)} key={`${v}-${i}`}>Kotak {v}</button>:<button onClick={()=>tap(v)} key={`${v}-${i}`}>{v}</button>)}</div><button onClick={()=>setResponse(r=>r.slice(0,-1))} disabled={!response.length}>Undo</button><button onClick={submit}>Kirim</button></>}{state==='Submitting'&&<p>Menyimpan…</p>}</>}{state==='Complete'&&<h2>Selesai</h2>}</section>
}
