using Microsoft.EntityFrameworkCore;
using SiapSD.Cognitive.Application;
using SiapSD.Cognitive.Domain;
using SiapSD.Cognitive.Infrastructure;
var b = WebApplication.CreateBuilder(args); b.Configuration.AddUserSecrets<Program>(optional: true); var cs = b.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Configure ConnectionStrings:DefaultConnection with user secrets."); b.Services.AddDbContext<SiapSDDbContext>(o => o.UseNpgsql(cs)); b.Services.AddScoped<IQuestionValidationService, QuestionValidationService>(); b.Services.AddScoped<IAdaptiveDifficultyService, AdaptiveDifficultyService>(); b.Services.AddScoped<IQuestionSelectionService, QuestionSelectionService>(); b.Services.AddSingleton<IWorkingMemoryEngine, WorkingMemoryEngine>(); b.Services.AddScoped<IAssessmentService, AssessmentService>(); b.Services.AddEndpointsApiExplorer(); b.Services.AddSwaggerGen(); b.Services.AddCors(o => o.AddDefaultPolicy(p => p.WithOrigins("http://127.0.0.1:5173", "http://localhost:5173").AllowAnyHeader().AllowAnyMethod())); var app = b.Build(); app.UseCors(); app.UseSwagger(); app.UseSwaggerUI(); using (var scope = app.Services.CreateScope()) { var db = scope.ServiceProvider.GetRequiredService<SiapSDDbContext>(); await SeedData.EnsureAsync(db); await CanonicalQuestionBankSeedData.EnsureAsync(db); }
app.MapGet("/api/children", async (SiapSDDbContext db) => await db.Children.ToListAsync()); app.MapPost("/api/children", async (Child x, SiapSDDbContext db) => { db.Children.Add(x); await db.SaveChangesAsync(); return Results.Created($"/api/children/{x.Id}", x); }); app.MapGet("/api/domains", async (SiapSDDbContext db) => await db.CognitiveDomains.Include(x => x.Subtests).ToListAsync()); app.MapGet("/api/subtests", async (SiapSDDbContext db) => await db.Subtests.ToListAsync()); app.MapGet("/api/questions", async (SiapSDDbContext db) => await db.Questions.Include(x => x.Options).Select(q => new { q.Id, q.Code, QuestionType = q.QuestionType.ToString(), q.Instruction, q.QuestionText, q.StimulusJson, Options = q.Options.Select(o => new { o.Code, o.Text, o.ImageUrl, o.Value, o.DisplayOrder }) }).ToListAsync()); app.MapGet("/api/assessment-blueprints", async (SiapSDDbContext db) => await db.AssessmentBlueprints.Include(x => x.Items).ToListAsync());
app.MapPost("/api/assessments/start", async (StartRequest x, IAssessmentService s) => Results.Ok(await s.StartAssessment(x.ChildId, x.BlueprintId))); app.MapGet("/api/assessments/{id:guid}", async (Guid id, IAssessmentService s) => (await s.GetAssessment(id)) is { } v ? Results.Ok(v) : Results.NotFound()); app.MapGet("/api/assessments/{id:guid}/next-question", async (Guid id, IAssessmentService s) => (await s.GetNextQuestion(id)) is { } q ? Results.Ok(new { q.Id, QuestionType = q.QuestionType.ToString(), q.Instruction, q.QuestionText, q.StimulusJson, Options = q.Options.Select(o => new { o.Code, o.Text, o.ImageUrl, o.Value, o.DisplayOrder }) }) : Results.NoContent()); app.MapPost("/api/assessments/{id:guid}/answer", async (Guid id, AnswerRequest x, IAssessmentService s) => { try { return Results.Ok(await s.SubmitAnswer(id, x.QuestionId, x.Answer, x.ResponseTimeMs, x.FirstInteraction)); } catch (ArgumentException ex) { return Results.BadRequest(new { error = ex.Message }); } }); app.MapPost("/api/assessments/{id:guid}/pause", async (Guid id, IAssessmentService s) => { await s.PauseAssessment(id); return Results.NoContent(); }); app.MapPost("/api/assessments/{id:guid}/resume", async (Guid id, IAssessmentService s) => { await s.ResumeAssessment(id); return Results.NoContent(); }); app.MapPost("/api/assessments/{id:guid}/complete", async (Guid id, IAssessmentService s) => { await s.CompleteAssessment(id); return Results.NoContent(); });
app.MapGet("/api/reports/{id:guid}", ReportEndpoint.Create); app.Run();
public record StartRequest(Guid ChildId, Guid BlueprintId); public record AnswerRequest(Guid QuestionId, string Answer, long ResponseTimeMs, bool FirstInteraction);
