namespace SiapSD.Cognitive.Domain;

public enum Gender { Unspecified, Female, Male, Other }
public enum AppUserRole { SuperAdmin, User }
public enum AssessmentStatus { NotStarted, InProgress, Paused, Completed, Cancelled }
public enum QuestionType { SingleChoice, ImageChoice, PatternChoice, MissingPart, OddOneOut, Sequence, DragSequence, MemorySequence, SpatialMemory, AuditorySequence, InstructionSequence, TargetDetection, VisualSearch, NumberInput, MathChoice, StoryProblem, InhibitoryControl, RuleSwitch, GridPlanning, SymbolMatching }

public class Child { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = ""; public string? Nickname { get; set; } public DateOnly BirthDate { get; set; } public Gender? Gender { get; set; } public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow; public int AgeInMonths(DateOnly? on = null) { var d = on ?? DateOnly.FromDateTime(DateTime.UtcNow); var m = (d.Year-BirthDate.Year)*12+d.Month-BirthDate.Month; return d.Day < BirthDate.Day ? Math.Max(0,m-1) : Math.Max(0,m); } }
public class AppUser { public Guid Id { get; set; } = Guid.NewGuid(); public string Username { get; set; } = ""; public string NormalizedUsername { get; set; } = ""; public string PasswordHash { get; set; } = ""; public AppUserRole Role { get; set; } = AppUserRole.User; public bool IsActive { get; set; } = true; public bool MustChangePassword { get; set; } = true; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime? LastLoginAtUtc { get; set; } }
public class CognitiveDomain { public Guid Id { get; set; } = Guid.NewGuid(); public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? Description { get; set; } public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; public List<Subtest> Subtests { get; set; } = []; }
public class Subtest { public Guid Id { get; set; } = Guid.NewGuid(); public Guid CognitiveDomainId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? Description { get; set; } public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; public CognitiveDomain? CognitiveDomain { get; set; } }
public class Question { public Guid Id { get; set; } = Guid.NewGuid(); public string Code { get; set; } = ""; public Guid CognitiveDomainId { get; set; } public Guid SubtestId { get; set; } public QuestionType QuestionType { get; set; } public int Difficulty { get; set; } public int AgeMinMonths { get; set; } public int AgeMaxMonths { get; set; } public string Instruction { get; set; } = ""; public string QuestionText { get; set; } = ""; public string? StimulusJson { get; set; } public string CorrectAnswerJson { get; set; } = ""; public string? Explanation { get; set; } public bool IsAnswerRandomized { get; set; } public bool IsPublished { get; set; } public int Version { get; set; } = 1; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow; public List<QuestionOption> Options { get; set; } = []; }
public class QuestionOption { public Guid Id { get; set; } = Guid.NewGuid(); public Guid QuestionId { get; set; } public string Code { get; set; } = ""; public string Text { get; set; } = ""; public string? ImageUrl { get; set; } public string? Value { get; set; } public int DisplayOrder { get; set; } public bool IsCorrect { get; set; } }
public class AssessmentBlueprint { public Guid Id { get; set; } = Guid.NewGuid(); public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? Description { get; set; } public bool IsActive { get; set; } = true; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public List<AssessmentBlueprintItem> Items { get; set; } = []; }
public class AssessmentBlueprintItem { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AssessmentBlueprintId { get; set; } public Guid CognitiveDomainId { get; set; } public Guid? SubtestId { get; set; } public int InitialDifficulty { get; set; } = 1; public int MinimumQuestions { get; set; } = 1; public int MaximumQuestions { get; set; } = 5; public int DisplayOrder { get; set; } public bool IsAdaptive { get; set; } = true; public string? BasalRuleJson { get; set; } public string? CeilingRuleJson { get; set; } }
public class AssessmentSession { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ChildId { get; set; } public Guid AssessmentBlueprintId { get; set; } public AssessmentStatus Status { get; set; } = AssessmentStatus.NotStarted; public DateTime? StartedAtUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public int AgeInMonthsAtAssessment { get; set; } public Guid? CurrentSubtestId { get; set; } public int CurrentQuestionIndex { get; set; } public long TotalDurationMs { get; set; } public string? PreAssessmentContextJson { get; set; } public string? PostAssessmentContextJson { get; set; } public List<AssessmentResponse> Responses { get; set; } = []; }
public class AssessmentResponse { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AssessmentSessionId { get; set; } public Guid QuestionId { get; set; } public int QuestionVersion { get; set; } public string QuestionSnapshotJson { get; set; } = ""; public Guid CognitiveDomainId { get; set; } public Guid SubtestId { get; set; } public int Difficulty { get; set; } public DateTime PresentedAtUtc { get; set; } public DateTime? FirstInteractionAtUtc { get; set; } public DateTime? AnsweredAtUtc { get; set; } public long? ResponseTimeMs { get; set; } public string? FirstAnswerJson { get; set; } public string FinalAnswerJson { get; set; } = ""; public bool IsCorrect { get; set; } public int AttemptCount { get; set; } = 1; public bool ChangedAnswer { get; set; } public bool HintUsed { get; set; } public bool Skipped { get; set; } public bool TimedOut { get; set; } public int QuestionOrder { get; set; } public long SessionElapsedMs { get; set; } public string? ResponseTelemetryJson { get; set; } }
public class AssessmentDomainScore { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AssessmentSessionId { get; set; } public Guid CognitiveDomainId { get; set; } public int RawScore { get; set; } public decimal InternalScore { get; set; } public string MetricsJson { get; set; } = "{}"; public string? InterpretationKey { get; set; } }
