// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiapSD.Cognitive.Infrastructure;

#nullable disable

namespace SiapSD.Cognitive.Infrastructure.Migrations
{
    [DbContext(typeof(SiapSDDbContext))]
    partial class SiapSDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentBlueprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AssessmentBlueprints");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentBlueprintItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentBlueprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("BasalRuleJson")
                        .HasColumnType("text");

                    b.Property<string>("CeilingRuleJson")
                        .HasColumnType("text");

                    b.Property<Guid>("CognitiveDomainId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("InitialDifficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdaptive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumQuestions")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubtestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBlueprintId");

                    b.ToTable("AssessmentBlueprintItems");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentDomainScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CognitiveDomainId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InternalScore")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("InterpretationKey")
                        .HasColumnType("text");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RawScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AssessmentDomainScores");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssessmentSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ChangedAnswer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CognitiveDomainId")
                        .HasColumnType("uuid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("FinalAnswerJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstAnswerJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstInteractionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HintUsed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PresentedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseTelemetryJson")
                        .HasColumnType("text");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionElapsedMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubtestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentSessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("AssessmentResponses");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeInMonthsAtAssessment")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssessmentBlueprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentSubtestId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostAssessmentContextJson")
                        .HasColumnType("text");

                    b.Property<string>("PreAssessmentContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AssessmentSessions");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.CognitiveDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CognitiveDomains");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMaxMonths")
                        .HasColumnType("integer");

                    b.Property<int>("AgeMinMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CognitiveDomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectAnswerJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswerRandomized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<string>("StimulusJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SubtestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.Subtest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CognitiveDomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CognitiveDomainId", "Code")
                        .IsUnique();

                    b.ToTable("Subtests");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentBlueprintItem", b =>
                {
                    b.HasOne("SiapSD.Cognitive.Domain.AssessmentBlueprint", null)
                        .WithMany("Items")
                        .HasForeignKey("AssessmentBlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentResponse", b =>
                {
                    b.HasOne("SiapSD.Cognitive.Domain.AssessmentSession", null)
                        .WithMany("Responses")
                        .HasForeignKey("AssessmentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.QuestionOption", b =>
                {
                    b.HasOne("SiapSD.Cognitive.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.Subtest", b =>
                {
                    b.HasOne("SiapSD.Cognitive.Domain.CognitiveDomain", "CognitiveDomain")
                        .WithMany("Subtests")
                        .HasForeignKey("CognitiveDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CognitiveDomain");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentBlueprint", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.AssessmentSession", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.CognitiveDomain", b =>
                {
                    b.Navigation("Subtests");
                });

            modelBuilder.Entity("SiapSD.Cognitive.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
