using SiapSD.Cognitive.Application; using SiapSD.Cognitive.Domain;
namespace SiapSD.Cognitive.Tests;
public class CoreTests {
 [Fact] public void Working_memory_scores_positions_and_errors(){var e=new WorkingMemoryEngine();var r=e.Evaluate(["A","B","C","D"],["A","B","D","C"]);Assert.Equal(2,r.CorrectPositions);Assert.False(r.FullyCorrect);Assert.Equal("OrderError",r.ErrorType);}
 [Fact] public void Working_memory_staircase_and_ceiling(){var e=new WorkingMemoryEngine();var p=new WorkingMemoryProgress(3,0,0,false);p=e.Next(p,true);p=e.Next(p,true);Assert.Equal(4,p.Span);p=e.Next(p,false);p=e.Next(p,false);Assert.True(p.Stop);}
 [Fact] public void Partial_memory_response_does_not_advance_span(){var e=new WorkingMemoryEngine();var partial=e.Evaluate(["A","B","C"],["A","C","B"]);var p=e.Next(new WorkingMemoryProgress(3,0,0,false),partial.FullyCorrect);Assert.Equal(3,p.Span);Assert.Equal(1,p.FailuresAtSpan);}
 [Fact] public void Working_memory_metrics_keep_partial_accuracy(){var e=new WorkingMemoryEngine();var r=new AssessmentResponse{Difficulty=3,IsCorrect=false,ResponseTimeMs=400,ResponseTelemetryJson="{\"sequenceLength\":3,\"correctPositions\":2,\"totalPositions\":3}"};var m=e.Metrics([r]);Assert.Equal(1,m.PartialCorrectTrials);Assert.Equal(2m/3m,m.AveragePositionAccuracy);}
 [Fact] public void AgeInMonths_handles_day_boundary(){var c=new Child{BirthDate=new DateOnly(2020,1,15)};Assert.Equal(60,c.AgeInMonths(new DateOnly(2025,1,15)));Assert.Equal(59,c.AgeInMonths(new DateOnly(2025,1,14)));}
 [Fact] public void Validation_rejects_invalid_question(){var r=new QuestionValidationService().Validate(new Question{Difficulty=6,AgeMinMonths=5,AgeMaxMonths=2});Assert.False(r.IsValid);Assert.NotEmpty(r.Errors);}
 [Theory][InlineData(1,false,false,1)][InlineData(5,true,true,5)] public void Adaptive_clamps(int current,bool a,bool b,int expected){Assert.Equal(expected,new AdaptiveDifficultyService().NextDifficulty(current,[a,b,a]));}
 [Fact] public void Three_correct_increases(){Assert.Equal(4,new AdaptiveDifficultyService().NextDifficulty(3,[true,true,true]));}
 [Fact] public void Two_incorrect_decreases(){Assert.Equal(2,new AdaptiveDifficultyService().NextDifficulty(3,[false,false]));}
 [Fact] public void Options_keep_correct_when_shuffled(){var o=new[]{new QuestionOption{Code="A"},new QuestionOption{Code="B",IsCorrect=true},new QuestionOption{Code="C"}};var shuffled=o.OrderBy(_=>Guid.NewGuid()).ToArray();Assert.Single(shuffled.Where(x=>x.IsCorrect));Assert.Equal("B",shuffled.Single(x=>x.IsCorrect).Code);}
 [Fact] public void Selection_uses_age_published_and_unused(){var d=Guid.NewGuid();var st=Guid.NewGuid();var used=Guid.NewGuid();var s=new AssessmentSession{AgeInMonthsAtAssessment=60,Responses=[new AssessmentResponse{QuestionId=used}]};var i=new AssessmentBlueprintItem{CognitiveDomainId=d,SubtestId=st};var qs=new[]{new Question{Id=used,CognitiveDomainId=d,SubtestId=st,Difficulty=1,AgeMinMonths=48,AgeMaxMonths=72,IsPublished=true},new Question{CognitiveDomainId=d,SubtestId=st,Difficulty=1,AgeMinMonths=48,AgeMaxMonths=72,IsPublished=true}};Assert.NotEqual(used,new QuestionSelectionService().Select(qs,s,i,1)!.Id);}
 [Fact] public void Content_validator_accepts_a_complete_canonical_question(){Assert.Empty(new QuestionContentValidator().Validate(ValidQuestion()));}
 [Theory][InlineData("DEV-X")][InlineData("")] public void Content_validator_requires_canonical_code(string code){var q=ValidQuestion();q.Code=code;Assert.Contains(new QuestionContentValidator().Validate(q),x=>x.Contains("canonical"));}
 [Theory][InlineData(0)][InlineData(6)] public void Content_validator_rejects_out_of_range_difficulty(int difficulty){var q=ValidQuestion();q.Difficulty=difficulty;Assert.Contains(new QuestionContentValidator().Validate(q),x=>x.Contains("difficulty"));}
 [Fact] public void Content_validator_rejects_invalid_age_duplicate_options_and_malformed_stimulus(){var q=ValidQuestion();q.AgeMinMonths=80;q.AgeMaxMonths=48;q.StimulusJson="{";q.Options.Add(new QuestionOption{Code="C",Text=" blue ",DisplayOrder=3});var errors=new QuestionContentValidator().Validate(q);Assert.Contains(errors,x=>x.Contains("invalid age"));Assert.Contains(errors,x=>x.Contains("duplicate options"));Assert.Contains(errors,x=>x.Contains("malformed stimulus"));}
 [Fact] public void Fingerprint_normalizes_case_whitespace_and_json_property_order(){var a=ValidQuestion();var b=ValidQuestion();b.Instruction="  CHOOSE   BLUE ";b.StimulusJson="{\"items\":[\"red\",\"blue\"],\"target\":\"blue\"}";Assert.Equal(QuestionContentValidator.Fingerprint(a),QuestionContentValidator.Fingerprint(b));b.Options[1].Text="green";Assert.NotEqual(QuestionContentValidator.Fingerprint(a),QuestionContentValidator.Fingerprint(b));}
 [Fact] public void Planning_bfs_validates_reachability_and_shortest_path(){Assert.True(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[1,1]],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[-1,0],[2,2],[],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[3,2],[],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[3,1]],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[0,0]],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[2,2]],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[0,1],[1,0]],4).Reachable);Assert.False(PlanningPathValidator.Validate(3,3,[0,0],[2,2],[[1,1]],3).Reachable);}
 static Question ValidQuestion(){var q=new Question{Code="CORE-TEST-001",QuestionType=QuestionType.SingleChoice,Difficulty=3,AgeMinMonths=48,AgeMaxMonths=84,Instruction="Choose blue",QuestionText="Pick the blue item",StimulusJson="{\"target\":\"blue\",\"items\":[\"red\",\"blue\"]}",CorrectAnswerJson="\"B\""};q.Options.AddRange([new QuestionOption{Code="A",Text="red",DisplayOrder=1},new QuestionOption{Code="B",Text="blue",DisplayOrder=2,IsCorrect=true}]);return q;}
}
