using SiapSD.Cognitive.Domain;
namespace SiapSD.Cognitive.Application;

public record ValidationResult(bool IsValid, IReadOnlyList<string> Errors) { public static ValidationResult Ok() => new(true, []); }
public interface IQuestionValidationService { ValidationResult Validate(Question question, bool domainExists = true, bool subtestExists = true); }
public class QuestionValidationService : IQuestionValidationService { public ValidationResult Validate(Question q, bool domainExists = true, bool subtestExists = true) { var e = new List<string>(); if (!domainExists) e.Add("Domain does not exist."); if (!subtestExists) e.Add("Subtest does not exist."); if (q.Difficulty is < 1 or > 5) e.Add("Difficulty must be 1-5."); if (q.AgeMinMonths < 0 || q.AgeMaxMonths < q.AgeMinMonths) e.Add("Invalid age range."); if (string.IsNullOrWhiteSpace(q.Instruction)) e.Add("Instruction is required."); if (!Enum.IsDefined(q.QuestionType)) e.Add("Unsupported question type."); if (string.IsNullOrWhiteSpace(q.StimulusJson) && string.IsNullOrWhiteSpace(q.QuestionText)) e.Add("Stimulus is required."); if (string.IsNullOrWhiteSpace(q.CorrectAnswerJson)) e.Add("Answer is required."); if (q.Options.GroupBy(x => x.Code).Any(g => string.IsNullOrWhiteSpace(g.Key) || g.Count() > 1)) e.Add("Duplicate option code."); if (q.Options.Count > 0 && !q.Options.Any(x => x.IsCorrect)) e.Add("Correct option is required."); return new(!e.Any(), e); } }
public interface IAdaptiveDifficultyService { int NextDifficulty(int current, IEnumerable<bool> recentResults); }
public class AdaptiveDifficultyService : IAdaptiveDifficultyService { public int NextDifficulty(int current, IEnumerable<bool> recent) { var r=recent.ToArray(); if(r.TakeLast(3).Count()==3 && r.TakeLast(3).All(x=>x)) return Math.Min(5,current+1); if(r.TakeLast(2).Count()==2 && r.TakeLast(2).All(x=>!x)) return Math.Max(1,current-1); return Math.Clamp(current,1,5); } }
public interface IQuestionSelectionService { Question? Select(IEnumerable<Question> questions, AssessmentSession session, AssessmentBlueprintItem item, int difficulty); }
public class QuestionSelectionService : IQuestionSelectionService { public Question? Select(IEnumerable<Question> qs, AssessmentSession s, AssessmentBlueprintItem i, int d) => qs.Where(q=>q.IsPublished && IsPlayable(q) && q.CognitiveDomainId==i.CognitiveDomainId && (!i.SubtestId.HasValue || q.SubtestId==i.SubtestId) && q.AgeMinMonths<=s.AgeInMonthsAtAssessment && q.AgeMaxMonths>=s.AgeInMonthsAtAssessment && !s.Responses.Select(r=>r.QuestionId).Contains(q.Id)).GroupBy(q=>Math.Abs(q.Difficulty-Math.Clamp(d,1,5))).OrderBy(g=>g.Key).FirstOrDefault()?.OrderBy(_=>Guid.NewGuid()).FirstOrDefault(); static bool IsPlayable(Question q) => q.QuestionType switch { QuestionType.TargetDetection or QuestionType.VisualSearch => q.StimulusJson?.Contains("\"items\"") == true, QuestionType.GridPlanning => q.StimulusJson?.Contains("\"start\"") == true, _ => true }; }
public static class QuestionExtensions { public static string DisplayKey(this Question q) => q.Code; }
public record ScoreResult(int RawScore, decimal InternalScore, string MetricsJson);
public interface ISubtestScorer { ScoreResult Score(IEnumerable<AssessmentResponse> responses); }
public class BasicSubtestScorer : ISubtestScorer { public ScoreResult Score(IEnumerable<AssessmentResponse> rr) { var r=rr.ToArray(); var raw=r.Count(x=>x.IsCorrect); var median=r.Where(x=>x.ResponseTimeMs.HasValue).Select(x=>x.ResponseTimeMs!.Value).OrderBy(x=>x).Skip(Math.Max(0,r.Count(x=>x.ResponseTimeMs.HasValue)/2)).FirstOrDefault(); var high=r.Select(x=>x.Difficulty).DefaultIfEmpty().Max(); return new(raw, r.Length==0?0:Math.Round(100m*raw/r.Length,2), $"{{\"medianResponseTimeMs\":{median},\"highestDifficultyReached\":{high}}}"); } }
public interface IAssessmentService { Task<AssessmentSession> StartAssessment(Guid childId, Guid blueprintId); Task<AssessmentSession?> GetAssessment(Guid id); Task<Question?> GetNextQuestion(Guid id); Task<AssessmentResponse> SubmitAnswer(Guid id, Guid questionId, string answer, long responseTimeMs, bool firstInteraction); Task PauseAssessment(Guid id); Task ResumeAssessment(Guid id); Task CompleteAssessment(Guid id); }
