using System.Text.Json;
using SiapSD.Cognitive.Domain;
namespace SiapSD.Cognitive.Application;
public sealed record WorkingMemorySettings(int MinSpan=2,int MaxSpan=7,int YoungerStart=2,int StandardStart=3,int OlderStart=4);
public sealed record WorkingMemoryTrialResult(int SequenceLength,int CorrectPositions,bool FullyCorrect,string ErrorType);
public sealed record WorkingMemoryProgress(int Span,int ConsecutiveCorrect,int FailuresAtSpan,bool Stop);
public sealed record WorkingMemoryMetrics(int TrialsAttempted,int FullyCorrectTrials,int PartialCorrectTrials,int HighestSpanAttempted,int HighestSpanFullyCorrect,int HighestStableSpan,decimal AveragePositionAccuracy,long MedianResponseTimeMs);
public interface IWorkingMemoryEngine { int InitialSpan(int ageMonths); WorkingMemoryTrialResult Evaluate(IReadOnlyList<string> expected,IReadOnlyList<string> response); WorkingMemoryProgress Next(WorkingMemoryProgress current,bool fullyCorrect); WorkingMemoryMetrics Metrics(IEnumerable<AssessmentResponse> responses); }
public sealed class WorkingMemoryEngine(WorkingMemorySettings? settings=null) : IWorkingMemoryEngine { readonly WorkingMemorySettings s=settings??new(); public int InitialSpan(int age)=>age<60?s.YoungerStart:age>=84?s.OlderStart:s.StandardStart; public WorkingMemoryTrialResult Evaluate(IReadOnlyList<string> e,IReadOnlyList<string> r){var c=e.Zip(r,(a,b)=>a==b).Count(x=>x);var full=c==e.Count&&r.Count==e.Count;var err=full?"None":r.Count<e.Count?"Omission":r.Count>e.Count?"ExtraResponse":r.Distinct().Count()!=r.Count?"DuplicateSelection":"OrderError";return new(e.Count,c,full,err);} public WorkingMemoryProgress Next(WorkingMemoryProgress p,bool ok){var correct=ok?p.ConsecutiveCorrect+1:0;var fails=ok?0:p.FailuresAtSpan+1;if(fails>=2)return p with{FailuresAtSpan=fails,Stop=true};if(correct>=2)return new(Math.Min(s.MaxSpan,p.Span+1),0,0,false);return p with{ConsecutiveCorrect=correct,FailuresAtSpan=fails};} public WorkingMemoryMetrics Metrics(IEnumerable<AssessmentResponse> rr){var a=rr.Select(r=>new{r, t=JsonDocument.Parse(r.ResponseTelemetryJson??"{}").RootElement}).ToArray();var spans=a.Select(x=>x.t.TryGetProperty("sequenceLength",out var v)?v.GetInt32():x.r.Difficulty).ToArray();var acc=a.Select(x=>x.t.TryGetProperty("correctPositions",out var c)&&x.t.TryGetProperty("totalPositions",out var n)&&n.GetInt32()>0?(decimal)c.GetInt32()/n.GetInt32():x.r.IsCorrect?1m:0m).ToArray();var stable=a.Where(x=>x.r.IsCorrect).GroupBy(x=>x.t.TryGetProperty("sequenceLength",out var v)?v.GetInt32():x.r.Difficulty).Where(g=>g.Count()>=2).Select(g=>g.Key).DefaultIfEmpty(0).Max();var times=a.Select(x=>x.r.ResponseTimeMs??0).OrderBy(x=>x).ToArray();return new(a.Length,a.Count(x=>x.r.IsCorrect),a.Count(x=>!x.r.IsCorrect&&acc[Array.IndexOf(a,x)]>0),spans.DefaultIfEmpty().Max(),a.Where(x=>x.r.IsCorrect).Select(x=>x.t.TryGetProperty("sequenceLength",out var v)?v.GetInt32():x.r.Difficulty).DefaultIfEmpty().Max(),stable,acc.Length==0?0:acc.Average(),times.Length==0?0:times[times.Length/2]);} }
public sealed record ChildMemoryQuestionDto(Guid Id,QuestionType QuestionType,string Instruction,string QuestionText,string? PresentationJson,IReadOnlyList<ChildMemoryOption> Options); public sealed record ChildMemoryOption(string Code,string Text,string? ImageUrl,int DisplayOrder);
